### ISSUE TITLE
About the full project

### ISSUE THREAD

**Issue by SharifMAbdullah** [ankitsankhyan/Chatapp#1]
Hello, I was following the youtube tutorial of Road Side Code on the MERN-Chat-App and found your repository while looking for solutions to some problems. 
I have a few questions to ask:
1. Whenever I try to run the project using RoadSideCoder's project, the packages don't match and i get errors. So how did you resolve these conflicting packages?
2.  Have you completed the full project? If so, can you push it to github soon?
3. Will you be able to contact me? I am also doing this project and facing some issues, perhaps working together would solve them?

Thanks in advance!

**Comment by ankitsankhyan** [comment]
sorry bro i have not done it yet will continue it later

**Comment by ankitsankhyan** [comment]
i would like to work on this project if you like here is my linkedin account link https://www.linkedin.com/in/ankit-sankhyan-82b565223/ , sorry for late reply
